#!/usr/bin/env python3
from pathlib import Path
from textwrap import dedent

import requests

SINDRESORHUS_URL = "https://raw.githubusercontent.com/sindresorhus/github-markdown-css/refs/heads/main/github-markdown-light.css"

BODY_EXTRA = """
  /* CUSTOM BODY STYLES ADDED BY generate-gh-css.py */
  min-width: 490px;
  max-width: 980px;
  padding: 45px;
  margin: 0 auto!important;
  /* END CUSTOM BODY STYLES */\
"""

CSS_OVERWRITES = """\
/* CUSTOM OVERWRITES ADDED BY generate-gh-css.py */
p, blockquote, ul, ol, dl, table, code, tr {
  color: #1f2328;
}
tr {
  border: initial;
}
blockquote {
  background-color: initial;
}
/* END CUSTOM OVERWRITES */
"""

def download_sindresorhus() -> str:
    # Download sindresorhus' github-markdown-light.css
    response = requests.get(SINDRESORHUS_URL)
    response.raise_for_status()
    return response.text


def overwrite_styles(css: str) -> str:
    # Add some missing styles to the body tag
    css = css.replace("body {", f"body {{{BODY_EXTRA}")
    # Unfortunately, JetBrains adds a bunch of top-level
    # styles that need to be manually overwritten here:
    css = f"{CSS_OVERWRITES}\n{css}"
    return css


def add_top_comment(css: str) -> str:
    # Add a comment at the top of the file to indicate that it was generated
    # and attributing the original source
    comment = dedent(f"""\
    /*
     * This file has been generated by: https://github.com/tpvasconcelos/howtos/blob/master/snippets/misc/generate-gh-css.py
     * Original author: sindresorhus
     * Original source: {SINDRESORHUS_URL}
     * Original License: MIT (https://github.com/sindresorhus/github-markdown-css/blob/main/license)
     */
    """)
    return f"{comment}\n{css}"




def main() -> None:
    css = download_sindresorhus()

    # Modify the CSS
    css = css.replace(".markdown-body", "body")
    css = overwrite_styles(css)
    css = add_top_comment(css)

    # Save the CSS to a file
    path = Path("snippets/misc/github-markdown.css")
    path.write_text(css)

    # Success!
    print(f"Saved the GitHub Markdown Light CSS to {path}")


if __name__ == '__main__':
    main()
